### ISSUE TITLE
build hook failing - can't find paster

### ISSUE THREAD

**Issue by ncoghlan** [ncoghlan/openshift-kallithea#8]
I broke something when merging in @GrahamDumpleton's changes in #4:

    remote: Stopping DIY cartridge
    remote: Stopping Postgres cartridge
    remote: Building git ref 'master', commit ccc0cef
    remote: /var/lib/openshift/54892c98fcf9335e5700006c/app-root/runtime/repo/.openshift/action_hooks/build: line 11: paster: command not found
    remote: An error occurred executing 'gear postreceive' (exit code: 127)
    remote: Error message: CLIENT_ERROR: Failed to execute action hook 'build' for 54892c98fcf9335e5700006c applicati

**Comment by ncoghlan** [comment]
Note that this was upgrading an instance that had previously been deployed with the old script.

**Comment by ncoghlan** [comment]
OK, so this isn't a bug - the change in the cartridge type from DIY to the official Python 2.7 cartridge means that you can't upgrade old instances, you have to start fresh. This is just for demos anyway, and you have to explicitly merge in quickstart changes to your app repo, so I think that's OK.

**Comment by thiagofmam** [comment]
Hi,

I get the same error. I already restart the application but not working. Can you help me?
